// <auto-generated />
namespace SysEntityFrameworkCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20191129 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191129));
        
        string IMigrationMetadata.Id
        {
            get { return "201911290700549_20191129"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
